-- YummyPro custom domains baseline.
-- Idempotente: puede ejecutarse sobre un entorno que ya tenga parte del esquema.

create schema if not exists private;

create table if not exists private.runtime_config(
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

insert into private.runtime_config(key,value,updated_at)
values('custom_domain_cname_target','domains.yummypro.online',now())
on conflict(key) do nothing;

create or replace function public.service_get_runtime_secret(p_name text)
returns text
language sql
security definer
set search_path=''
as $$
  select ds.decrypted_secret
  from vault.decrypted_secrets ds
  where ds.name=p_name
  order by ds.updated_at desc nulls last,ds.created_at desc
  limit 1
$$;

revoke all on function public.service_get_runtime_secret(text) from public,anon,authenticated;
grant execute on function public.service_get_runtime_secret(text) to service_role;

create or replace function public.service_get_runtime_config(p_key text)
returns text
language sql
security definer
set search_path=''
as $
  select rc.value
  from private.runtime_config rc
  where rc.key=p_key
  limit 1
$;

revoke all on function public.service_get_runtime_config(text) from public,anon,authenticated;
grant execute on function public.service_get_runtime_config(text) to service_role;

alter table public.restaurants add column if not exists custom_domain text;

create or replace function private.normalize_custom_hostname(p_hostname text)
returns text
language plpgsql
immutable
set search_path=''
as $$
declare v_host text;
begin
  v_host:=lower(btrim(coalesce(p_hostname,'')));
  v_host:=regexp_replace(v_host,'^https?://','','i');
  v_host:=regexp_replace(v_host,'/.*$','');
  v_host:=regexp_replace(v_host,'\\.$','');
  if v_host='' or length(v_host)>253 then raise exception 'Dominio inválido'; end if;
  if v_host !~ '^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+$' then
    raise exception 'Dominio inválido';
  end if;
  return v_host;
end
$$;

create table if not exists public.business_custom_domains(
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  hostname text not null,
  status text not null default 'pending_dns',
  verification_token uuid not null default gen_random_uuid(),
  ssl_status text not null default 'pending',
  provider text not null default 'cloudflare_saas',
  provider_hostname_id text,
  verified_at timestamptz,
  activated_at timestamptz,
  last_checked_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists(select 1 from pg_constraint where conname='business_custom_domains_status_check' and conrelid='public.business_custom_domains'::regclass) then
    alter table public.business_custom_domains
      add constraint business_custom_domains_status_check
      check(status in ('pending_dns','dns_verified','provisioning','active','failed','disabled'));
  end if;
  if not exists(select 1 from pg_constraint where conname='business_custom_domains_ssl_status_check' and conrelid='public.business_custom_domains'::regclass) then
    alter table public.business_custom_domains
      add constraint business_custom_domains_ssl_status_check
      check(ssl_status in ('pending','initializing','active','error'));
  end if;
  if not exists(select 1 from pg_constraint where conname='business_custom_domains_hostname_normalized' and conrelid='public.business_custom_domains'::regclass) then
    alter table public.business_custom_domains
      add constraint business_custom_domains_hostname_normalized
      check(hostname=lower(hostname) and hostname !~ '[[:space:]:/]');
  end if;
end
$$;

create unique index if not exists business_custom_domains_hostname_live_uq
  on public.business_custom_domains(lower(hostname))
  where status<>'disabled';
create unique index if not exists business_custom_domains_one_active_uq
  on public.business_custom_domains(restaurant_id)
  where status='active';
create unique index if not exists business_custom_domains_one_pending_uq
  on public.business_custom_domains(restaurant_id)
  where status in ('pending_dns','dns_verified','provisioning');
create index if not exists business_custom_domains_restaurant_idx
  on public.business_custom_domains(restaurant_id,status);

alter table public.business_custom_domains enable row level security;
revoke all on table public.business_custom_domains from anon,authenticated;
grant all on table public.business_custom_domains to service_role;
grant usage,select on sequence public.business_custom_domains_id_seq to service_role;

create or replace function public.get_business_custom_domain(p_restaurant_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_active jsonb;
  v_pending jsonb;
  v_cname_target text:='domains.yummypro.online';
begin
  if (select auth.uid()) is null or not public.can_manage_restaurant(p_restaurant_id) then
    raise exception 'No autorizado';
  end if;

  select nullif(rc.value,'') into v_cname_target
  from private.runtime_config rc
  where rc.key='custom_domain_cname_target'
  limit 1;
  v_cname_target:=coalesce(v_cname_target,'domains.yummypro.online');

  select jsonb_build_object(
    'hostname',d.hostname,'status',d.status,'ssl_status',d.ssl_status,
    'verified_at',d.verified_at,'activated_at',d.activated_at
  ) into v_active
  from public.business_custom_domains d
  where d.restaurant_id=p_restaurant_id and d.status='active'
  order by d.activated_at desc nulls last,d.id desc limit 1;

  select jsonb_build_object(
    'hostname',d.hostname,'status',d.status,'ssl_status',d.ssl_status,
    'verification_record_name','_yummypro.'||d.hostname,
    'verification_record_value','yummypro-verification='||d.verification_token::text,
    'cname_target',v_cname_target,'verified_at',d.verified_at,
    'last_checked_at',d.last_checked_at,'last_error',d.last_error
  ) into v_pending
  from public.business_custom_domains d
  where d.restaurant_id=p_restaurant_id
    and d.status in ('pending_dns','dns_verified','provisioning','failed')
  order by d.created_at desc,d.id desc limit 1;

  return jsonb_build_object('active',v_active,'pending',v_pending);
end
$$;

create or replace function public.request_business_custom_domain(p_restaurant_id bigint,p_hostname text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_host text;
begin
  if (select auth.uid()) is null or not public.can_manage_restaurant(p_restaurant_id) then
    raise exception 'No autorizado';
  end if;
  if not exists(
    select 1 from public.restaurants r
    left join public.subscription_plans p on p.id=r.subscription_plan_id
    where r.id=p_restaurant_id and r.active is true
      and lower(coalesce(r.subscription_status,''))='active'
      and lower(btrim(coalesce(p.name,r.subscription_plan,'')))='pro'
  ) then
    raise exception 'Los dominios personalizados están disponibles solo para cuentas PRO activas';
  end if;

  v_host:=private.normalize_custom_hostname(p_hostname);
  if v_host='yummypro.online' or v_host like '%.yummypro.online'
     or v_host='github.io' or v_host like '%.github.io'
     or v_host='supabase.co' or v_host like '%.supabase.co' then
    raise exception 'Ese dominio está reservado';
  end if;

  if exists(
    select 1 from public.business_custom_domains d
    where lower(d.hostname)=v_host and d.restaurant_id<>p_restaurant_id and d.status<>'disabled'
  ) then raise exception 'Ese dominio ya está vinculado a otro negocio'; end if;

  if exists(
    select 1 from public.business_custom_domains d
    where d.restaurant_id=p_restaurant_id and lower(d.hostname)=v_host
      and d.status in ('pending_dns','dns_verified','provisioning','failed','active')
  ) then return public.get_business_custom_domain(p_restaurant_id); end if;

  update public.business_custom_domains set status='disabled',updated_at=now()
  where restaurant_id=p_restaurant_id and status in ('pending_dns','dns_verified','provisioning','failed');

  insert into public.business_custom_domains(restaurant_id,hostname,status,verification_token,ssl_status,provider,created_at,updated_at)
  values(p_restaurant_id,v_host,'pending_dns',gen_random_uuid(),'pending','cloudflare_saas',now(),now());

  return public.get_business_custom_domain(p_restaurant_id);
exception when unique_violation then
  raise exception 'Ese dominio ya está en proceso de vinculación';
end
$$;

create or replace function public.remove_business_custom_domain(p_restaurant_id bigint,p_hostname text default null)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_host text;
begin
  if (select auth.uid()) is null or not public.can_manage_restaurant(p_restaurant_id) then
    raise exception 'No autorizado';
  end if;
  if p_hostname is not null and btrim(p_hostname)<>'' then
    v_host:=private.normalize_custom_hostname(p_hostname);
  end if;
  update public.business_custom_domains set status='disabled',updated_at=now()
  where restaurant_id=p_restaurant_id and status<>'disabled'
    and (v_host is null or lower(hostname)=v_host);
  update public.restaurants r set custom_domain=null,updated_at=now()
  where r.id=p_restaurant_id and (v_host is null or lower(coalesce(r.custom_domain,''))=v_host);
  return public.get_business_custom_domain(p_restaurant_id);
end
$$;

revoke all on function public.get_business_custom_domain(bigint) from public,anon;
revoke all on function public.request_business_custom_domain(bigint,text) from public,anon;
revoke all on function public.remove_business_custom_domain(bigint,text) from public,anon;
grant execute on function public.get_business_custom_domain(bigint) to authenticated,service_role;
grant execute on function public.request_business_custom_domain(bigint,text) to authenticated,service_role;
grant execute on function public.remove_business_custom_domain(bigint,text) to authenticated,service_role;

create or replace function private.enforce_verified_custom_domain()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare v_host text;
begin
  if tg_op='UPDATE' and new.custom_domain is not distinct from old.custom_domain then return new; end if;
  if new.custom_domain is null or btrim(new.custom_domain)='' then new.custom_domain:=null; return new; end if;
  v_host:=private.normalize_custom_hostname(new.custom_domain);
  if not exists(
    select 1 from public.business_custom_domains d
    where d.restaurant_id=new.id and lower(d.hostname)=v_host and d.status='active'
  ) then
    raise exception 'El dominio personalizado todavía no está verificado y activo';
  end if;
  new.custom_domain:=v_host;
  return new;
end
$$;

drop trigger if exists restaurants_verified_custom_domain_guard on public.restaurants;
create trigger restaurants_verified_custom_domain_guard
before insert or update of custom_domain on public.restaurants
for each row execute function private.enforce_verified_custom_domain();
